version: 2.1

parameters:
    trigger-workflows:
        type: boolean
        default: true
    run-design-tokens:
        type: boolean
        default: false
    run-component-styles:
        type: boolean
        default: false
    run-icons:
        type: boolean
        default: false
    run-react-components:
        type: boolean
        default: false

workflows:
    version: 2
    ci:
        when: << pipeline.parameters.trigger-workflows >>
        jobs:
            - trigger-workflows-job
            - run-release:
                  filters:
                      branches:
                          only: circle-ci-release
    design-tokens:
        when: << pipeline.parameters.run-design-tokens >>
        jobs:
            - design-tokens-job
    component-styles:
        when: << pipeline.parameters.run-component-styles >>
        jobs:
            - component-styles-job
    icons:
        when: << pipeline.parameters.run-icons >>
        jobs:
            - icons-job
    react-components:
        when: << pipeline.parameters.run-react-components >>
        jobs:
            - react-components-job

jobs:
    run-release:
        docker:
            - image: circleci/node:14
        steps:
            - run: echo "Running becaause branch is main"
    trigger-workflows-job:
        docker:
            - image: circleci/node:14
        steps:
            - checkout
            - run:
                  name: Install npm Dependencies
                  command: npm ci
            - run:
                  name: Trigger Workflows
                  command: CIRCLECI_API_TOKEN=$PERSONAL_TOKEN GIT_BRANCH=$CIRCLE_BRANCH node --unhandled-rejections=strict ./.circleci/triggerWorkflows.js
    design-tokens-job:
        docker:
            - image: circleci/node:14
        working_directory: ~/project/packages/design-tokens
        steps:
            - checkout:
                  path: ~/project
            - run:
                  name: Install npm Dependencies
                  command: npm ci
            - run:
                  name: Tests
                  command: npm test
    component-styles-job:
        docker:
            - image: circleci/node:14
        working_directory: ~/project/packages/component-styles
        steps:
            - checkout:
                  path: ~/project
            - run:
                  name: Install npm Dependencies
                  command: npm ci
            - run:
                  name: Tests
                  command: npm test
    icons-job:
        docker:
            - image: circleci/node:14
        working_directory: ~/project/packages/icons
        steps:
            - checkout:
                  path: ~/project
            - run:
                  name: Install npm Dependencies
                  command: npm ci
            - run:
                  name: Tests
                  command: npm test
    react-components-job:
        docker:
            - image: circleci/node:14
        working_directory: ~/project/packages/react-components
        steps:
            - checkout:
                  path: ~/project
            - run:
                  name: Install npm Dependencies
                  command: npm ci
            - run:
                  name: Tests
                  command: npm test
