# See https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-user-key for getting GitHub write access
version: 2.1

workflows:
    version: 2
    publish-packages:
        jobs:
            - check-package-versions-job:
                  filters:
                      branches:
                          only:
                              - /^.+custom-release.*/
            - publish-packages-job:
                  filters:
                      branches:
                          only:
                              - main
                              - /^.+custom-release.*/
    pull-request-checker:
        jobs:
            - check-package-versions-job:
                  filters:
                      branches:
                          only:
                              - /^.*normal-release.*/
            - pull-request-checker-job:
                  requires:
                      - check-package-versions-job
                  filters:
                      branches:
                          ignore:
                              - main
                              - /^.+custom-release.*/
jobs:
    check-package-versions-job:
        docker:
            - image: cimg/node:14.15.5
        steps:
            - checkout
            - run:
                  name: Check package versions
                  command: chmod u+x ./.circleci/checkPackageVersions.sh && ./.circleci/checkPackageVersions.sh $CIRCLE_BRANCH
    publish-packages-job:
        docker:
            - image: cimg/node:14.15.5
        steps:
            - add_ssh_keys:
                  fingerprints:
                      - 95:05:01:71:62:53:0f:b9:3d:bd:a8:97:03:08:42:3c
            - checkout
            - run:
                  name: Set up Git Config
                  command: git config user.email "danlevy124@gmail.com" && git config user.name "CI"
            - run:
                  name: Track remote branch
                  command: git branch --set-upstream-to origin/$CIRCLE_BRANCH
            - run:
                  name: Publish Packages
                  command: chmod u+x ./.circleci/publishPackages.sh && ./.circleci/publishPackages.sh $CIRCLE_BRANCH $NPM_TOKEN $NETLIFY_AUTH_TOKEN $NETLIFY_REACT_DOCS_ID
    pull-request-checker-job:
        docker:
            - image: cimg/node:14.15.5
        steps:
            - checkout
            - run:
                  name: Concatenate package-lock.json Files for all Packages into combined-package-lock.txt File
                  command: ls ./packages | awk -F packages '{printf "\"packages/%s/package-lock.json\" ", $1}' | xargs cat > ./combined-package-lock.txt && cat ./package-lock.json >> ./combined-package-lock.txt
            - restore_cache:
                  key: node-modules-all-packages-v2-{{ checksum "combined-package-lock.txt" }}
            - run:
                  name: Pull Request Checker
                  command: chmod u+x ./.circleci/pullRequestChecker.sh && ./.circleci/pullRequestChecker.sh $NETLIFY_AUTH_TOKEN $NETLIFY_REACT_DOCS_ID
            - save_cache:
                  paths:
                      - ./node_modules
                      - ./packages/design-tokens/node_modules
                      - ./packages/global-web-styles/node_modules
                      - ./packages/icons/node_modules
                      - ./packages/react-components/node_modules
                  key: node-modules-all-packages-v2-{{ checksum "combined-package-lock.txt" }}
