version: 2.1

parameters:
    run-design-tokens:
        type: boolean
        default: false
    run-component-styles:
        type: boolean
        default: false
    run-icons:
        type: boolean
        default: false
    run-react-components:
        type: boolean
        default: false

workflows:
    version: 2
    ci:
        jobs:
            - trigger-workflows-job
    design-tokens:
        when: << pipeline.parameters.run-design-tokens >>
        jobs:
            - design-tokens-job
    component-styles:
        when: << pipeline.parameters.run-component-styles >>
        jobs:
            - component-styles-job
    icons:
        when: << pipeline.parameters.run-icons >>
        jobs:
            - icons-job
    react-components:
        when: << pipeline.parameters.run-react-components >>
        jobs:
            - react-components-job

jobs:
    trigger-workflows-job:
        docker:
            - image: circleci/node:10
        steps:
            - run: echo $TEST
            - checkout
            - run:
                  name: Install npm Dependencies
                  command: npm ci
            - run:
                  name: Trigger Workflows
                  command: CIRCLE_CI_TOKEN=$PERSONAL_TOKEN node ./.circleci/triggerWorkflows.js
    design-tokens-job:
        docker:
            - image: circleci/node:10
        working_directory: ~/packages/design-tokens
        steps:
            - checkout
            - run:
                  name: Print working directory
                  command: |
                      echo pwd
    component-styles-job:
        docker:
            - image: circleci/node:10
        working_directory: ~/packages/component-styles
        steps:
            - checkout
            - run:
                  name: Print working directory
                  command: |
                      echo pwd
    icons-job:
        docker:
            - image: circleci/node:10
        working_directory: ~/packages/icons
        steps:
            - checkout
            - run:
                  name: Print working directory
                  command: |
                      echo pwd
    react-components-job:
        docker:
            - image: circleci/node:10
        working_directory: ~/packages/react-components
        steps:
            - checkout
            - run:
                  name: Print working directory
                  command: |
                      echo pwd
