//This is an auto-generated file

export { default as BarChartIcon } from "../assets/svg/BarChartIcon.svg"
export { default as BellIcon } from "../assets/svg/BellIcon.svg"
export { default as CalendarIcon } from "../assets/svg/CalendarIcon.svg"
export { default as CameraIcon } from "../assets/svg/CameraIcon.svg"
export { default as CheckIcon } from "../assets/svg/CheckIcon.svg"
export { default as ChevronDownIcon } from "../assets/svg/ChevronDownIcon.svg"
export { default as ChevronLeftIcon } from "../assets/svg/ChevronLeftIcon.svg"
export { default as ChevronRightIcon } from "../assets/svg/ChevronRightIcon.svg"
export { default as ChevronUpIcon } from "../assets/svg/ChevronUpIcon.svg"
export { default as DivisionIcon } from "../assets/svg/DivisionIcon.svg"
export { default as HamburgerIcon } from "../assets/svg/HamburgerIcon.svg"
export { default as MinusIcon } from "../assets/svg/MinusIcon.svg"
export { default as MultiplicationIcon } from "../assets/svg/MultiplicationIcon.svg"
export { default as PlusIcon } from "../assets/svg/PlusIcon.svg"
